name: medihub
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  provider: ^4.3.2+3
  fluentui_system_icons: ^1.1.91
  material_design_icons_flutter: ^4.0.5855
  flutter_swiper: ^1.1.6
  fluttertoast: ^7.1.6
  flutter_tags: ^0.4.9+1
  modal_progress_hud: ^0.1.3
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/
   

